version: "3.9"
services:
  project:
    image: vintage-vault
    container_name: vintage-vault
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=postgresql-db
      - PORT=5432
    volumes:
      - .:/project
    depends_on: # wait for the database container to be ready
      - db
  db:
    image: postgres:14.4
    container_name: postgresql-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
